import uuid
from datetime import datetime
from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship
from database.connection import Base

def uid(): return mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
class Website(Base):
 __tablename__="websites"; id:Mapped[str]=uid(); domain_id:Mapped[str]=mapped_column(ForeignKey("domains.id"),unique=True,index=True); final_url:Mapped[str|None]=mapped_column(Text); status_code:Mapped[int|None]=mapped_column(Integer); title:Mapped[str|None]=mapped_column(Text); meta_description:Mapped[str|None]=mapped_column(Text); language:Mapped[str|None]=mapped_column(String(32)); favicon_url:Mapped[str|None]=mapped_column(Text); content_type:Mapped[str|None]=mapped_column(String(255)); server:Mapped[str|None]=mapped_column(String(255)); page_size:Mapped[int|None]=mapped_column(Integer); redirect_chain:Mapped[str|None]=mapped_column(Text); response_headers:Mapped[str|None]=mapped_column(Text); headings:Mapped[str|None]=mapped_column(Text); page_text:Mapped[str|None]=mapped_column(Text); image_count:Mapped[int]=mapped_column(Integer,default=0); script_count:Mapped[int]=mapped_column(Integer,default=0); stylesheet_count:Mapped[int]=mapped_column(Integer,default=0); robots_url:Mapped[str|None]=mapped_column(Text); sitemap_url:Mapped[str|None]=mapped_column(Text); updated_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow); domain=relationship("Domain",back_populates="website")
class CompanyProfile(Base):
 __tablename__="company_profiles"; id:Mapped[str]=uid(); domain_id:Mapped[str]=mapped_column(ForeignKey("domains.id"),unique=True,index=True); name:Mapped[str|None]=mapped_column(String(500)); legal_name:Mapped[str|None]=mapped_column(String(500)); description:Mapped[str|None]=mapped_column(Text); industry:Mapped[str|None]=mapped_column(String(255)); address:Mapped[str|None]=mapped_column(Text); city:Mapped[str|None]=mapped_column(String(255)); state:Mapped[str|None]=mapped_column(String(255)); country:Mapped[str|None]=mapped_column(String(255)); postal_code:Mapped[str|None]=mapped_column(String(64)); contact_page:Mapped[str|None]=mapped_column(Text); about_page:Mapped[str|None]=mapped_column(Text); careers_page:Mapped[str|None]=mapped_column(Text); pricing_page:Mapped[str|None]=mapped_column(Text); services:Mapped[str|None]=mapped_column(Text); business_hours:Mapped[str|None]=mapped_column(Text); domain=relationship("Domain",back_populates="company_profile")
class Contact(Base):
 __tablename__="contacts"; id:Mapped[str]=uid(); domain_id:Mapped[str]=mapped_column(ForeignKey("domains.id"),index=True); kind:Mapped[str]=mapped_column(String(20),index=True); value:Mapped[str]=mapped_column(String(500)); source_url:Mapped[str|None]=mapped_column(Text); domain=relationship("Domain",back_populates="contacts")
class SocialProfile(Base):
 __tablename__="social_profiles"; id:Mapped[str]=uid(); domain_id:Mapped[str]=mapped_column(ForeignKey("domains.id"),index=True); platform:Mapped[str]=mapped_column(String(64),index=True); url:Mapped[str]=mapped_column(Text); domain=relationship("Domain",back_populates="social_profiles")
class Technology(Base):
 __tablename__="technologies"; id:Mapped[str]=uid(); domain_id:Mapped[str]=mapped_column(ForeignKey("domains.id"),index=True); name:Mapped[str]=mapped_column(String(128),index=True); category:Mapped[str]=mapped_column(String(64)); evidence:Mapped[str|None]=mapped_column(Text); domain=relationship("Domain",back_populates="technologies")
class SEOData(Base):
 __tablename__="seo_data"; id:Mapped[str]=uid(); domain_id:Mapped[str]=mapped_column(ForeignKey("domains.id"),unique=True,index=True); canonical_url:Mapped[str|None]=mapped_column(Text); robots:Mapped[str|None]=mapped_column(Text); open_graph:Mapped[str|None]=mapped_column(Text); twitter_cards:Mapped[str|None]=mapped_column(Text); structured_data:Mapped[str|None]=mapped_column(Text); word_count:Mapped[int]=mapped_column(Integer,default=0); images_with_alt:Mapped[int]=mapped_column(Integer,default=0); images_without_alt:Mapped[int]=mapped_column(Integer,default=0); domain=relationship("Domain",back_populates="seo")
class DNSRecord(Base):
 __tablename__="dns_records"; id:Mapped[str]=uid(); domain_id:Mapped[str]=mapped_column(ForeignKey("domains.id"),index=True); record_type:Mapped[str]=mapped_column(String(20),index=True); record_value:Mapped[str]=mapped_column(Text); error:Mapped[str|None]=mapped_column(Text); domain=relationship("Domain",back_populates="dns_records")
class SecurityData(Base):
 __tablename__="security_data"; id:Mapped[str]=uid(); domain_id:Mapped[str]=mapped_column(ForeignKey("domains.id"),unique=True,index=True); https_available:Mapped[bool]=mapped_column(Boolean,default=False); hsts:Mapped[str|None]=mapped_column(Text); csp:Mapped[str|None]=mapped_column(Text); x_frame_options:Mapped[str|None]=mapped_column(Text); x_content_type_options:Mapped[str|None]=mapped_column(Text); referrer_policy:Mapped[str|None]=mapped_column(Text); permissions_policy:Mapped[str|None]=mapped_column(Text); domain=relationship("Domain",back_populates="security")
class Scan(Base):
 __tablename__="scans"; id:Mapped[str]=uid(); domain_id:Mapped[str]=mapped_column(ForeignKey("domains.id"),index=True); status:Mapped[str]=mapped_column(String(32)); errors:Mapped[str|None]=mapped_column(Text); started_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); completed_at:Mapped[datetime|None]=mapped_column(DateTime); domain=relationship("Domain",back_populates="scans")
